spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://10.0.0.11:9411

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.0.11:8761/eureka/,http://10.0.0.11:8861/eureka/,http://10.0.0.11:8961/eureka/
