spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.0.1:8761/eureka/ http://10.0.0.1:8861/eureka/ http://10.0.0.1:8961/eureka/
