spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://10.0.0.11:8084
  zipkin:
    base-url: http://10.0.0.11:9411
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/itoken-service-admin
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8501

mybatis:
  type-aliases-package: com.teamlab.itoken.service.admin.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.0.11:8761/eureka/,http://10.0.0.11:8861/eureka/,http://10.0.0.11:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info